### PR TITLE
Add callback to child_process exec to get test results, use only on windows.

### PR DESCRIPTION
**Pull request by LorbusChris**
I added a callback to habe the results output to console. With exec the child process is called in a new shell and buffered. So we only get the results after the test has finished via callback. 
For large tests one would maybe have to set the maxBuffer option on exec.

I think it might therefore make sense to fall back to using fork with all other OS. 
Then you also get the results as you go and don't have to wait until the end to see them. (not on Windows obvsly)

### CODE REVIEW

**Comment by nkbt** [comment]
I reckon it is better to use spawn instead with `stdio: 'inherit'`.

**Comment by nkbt** [comment]
Closed in favour of #32

**Comment by nkbt** [comment]
Thank you a lot for participating, by the way!

**Comment by LorbusChris** [comment]
You're welcome :smile:

**Pull request closed without merging**
